# Generated by Django 6.0.6 on 2026-07-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
    ]
