# Generated by Django 6.0.6 on 2026-07-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0002_auto_20260702_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='learning_goal',
            field=models.TextField(blank=True),
        ),
    ]
