# Generated by Django 6.0.6 on 2026-07-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0005_booking_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('UGX', 'UGX — Ugandan Shilling'), ('USD', 'USD — US Dollar'), ('EUR', 'EUR — Euro'), ('GBP', 'GBP — British Pound'), ('KES', 'KES — Kenyan Shilling'), ('TZS', 'TZS — Tanzanian Shilling')], default='UGX', max_length=3),
        ),
    ]
