# Generated by Django 6.0.6 on 2026-07-08 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0008_message_is_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('tutor', 'Tutor')], max_length=10)),
                ('report_type', models.CharField(choices=[('tutor', 'A Tutor'), ('student', 'A Student'), ('platform', 'Platform Issue')], max_length=10)),
                ('target_user', models.CharField(blank=True, max_length=100)),
                ('reason', models.CharField(choices=[('bad_behavior', 'Bad Behaviour'), ('spam', 'Spam'), ('fake_account', 'Fake Account'), ('inappropriate_content', 'Inappropriate Content'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
