# Generated by Django 6.0.6 on 2026-07-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0011_booking_cancellation_reason_booking_proposed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='faculty',
            field=models.CharField(default='Faculty of Science and Technology', max_length=255),
        ),
    ]
